### ISSUE TITLE
Is project abandonend or just works great and doesnt need to be improved?

### ISSUE THREAD

**Issue by aexol** [FlacheQL/FlacheQL#94]
I would add this to be a part of my graphql tools but I am worried if maintainer of this repo is active :)

**Comment by fairlycasual** [comment]
Hi Artur,

Thanks for reaching out! We have all moved to different stages in our professional careers. With that being said, was there a specific improvement or update you'd like to see with the caching engine?

I would be happy to look into implementation in my spare time, or feel free to improve on it yourself and submit a pull request!

The caching engine is written in vanilla ES6 JavaScript, and in the spirit of open-source technology, we welcome any upgrades you have in mind!

Regards,
Will Howard

Sent from my iPhone

On Jan 9, 2019, at 1:37 AM, Artur Czemiel <notifications@github.com<mailto:notifications@github.com>> wrote:


I would add this to be a part of my graphql tools but I am worried if maintainer of this repo is active :)

**Comment by aexol** [comment]
Thank you I will try to incorporate that into graphql-editor generated frontend lib
